# husk: docker network create eshop-on-web-net
networks:
  eshop-on-web-net:
    external: true

services:
  eshopwebmvc:
    container_name: eshopwebmvc  
    image: ${DOCKER_REGISTRY-}eshopwebmvc
    build:
      context: .
      dockerfile: src/Web/Dockerfile
    depends_on:
      - sqlserver
      - storage_rabbitmq
    networks:
      - eshop-on-web-net
    environment:
     - ASPNETCORE_ENVIRONMENT=Docker
     - ASPNETCORE_URLS=http://+:8080
    ports:
      - "5106:8080"
    volumes:
      - ~/.aspnet/https:/root/.aspnet/https:ro
      - ~/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro
      - ./keys:/keys

  sqlserver:
    container_name: sqlserver
    image: mcr.microsoft.com/azure-sql-edge
    ports:
      - "1433:1433"
    environment:
      - SA_PASSWORD=@someThingComplicated1234
      - ACCEPT_EULA=Y
    networks:
      - eshop-on-web-net
    volumes:
      - sqlserver_data:/var/lib/sqlserver/data

volumes:
  sqlserver_data:


