services:
  order-db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: orders
    labels:
      co.elastic.logs/enabled: "true"
      co.elastic.logs/service: "order-db"
      co.elastic.logs/env: "dev"
    ports:
      - "5433:5432"  # host port 5433 maps to container 5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      retries: 5
      timeout: 5s
    networks:
      - eshop-on-web-net

  order-api:
    build: .
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:password@order-db:5432/orders
      RABBITMQ_URL: amqp://guest:guest@rabbitmq/
    labels:
      co.elastic.logs/enabled: "true"
      co.elastic.logs/service: "order-api"
      co.elastic.logs/env: "dev"
      co.elastic.logs/processors: >-
        [{"add_fields": {"target": "service", "fields": {"name": "order-api", "env": "dev"}}}]
    ports:
      - "8001:8001"
    depends_on:
      order-db:
        condition: service_healthy
    networks:
      eshop-on-web-net:
        aliases:
          - order
    command: uvicorn app.main:app --host 0.0.0.0 --port 8001 --reload

networks:
  eshop-on-web-net:
    external: true
