networks:
  eshop-on-web-net:
    external: true
services:
  storage_app:
    build: .
    depends_on:
      - storage_db
    ports:
      - "3000:3000"
    labels:
      co.elastic.logs/enabled: "true"
      co.elastic.logs/service: "storage_app"
      co.elastic.logs/env: "dev"
    environment:
      DATABASE_HOST: storage_db
      DATABASE_PORT: 5432
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_NAME: storage-db
      RABBITMQ_URI: amqp://guest:guest@storage_rabbitmq:5672
    networks:
      - eshop-on-web-net

  storage_db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: storage-db
    labels:
      co.elastic.logs/enabled: "true"
      co.elastic.logs/service: "storage-db"
      co.elastic.logs/env: "dev"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - eshop-on-web-net

volumes:
  postgres_data:
  pgadmin_data: