networks:
  eshop-on-web-net:
    external: true
    
services:
  storage-app:
    build: .
    depends_on:
      storage-db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    ports:
      - "3000:3000"
    labels:
      co.elastic.logs/enabled: "true"
      co.elastic.logs/service: "storage_app"
      co.elastic.logs/env: "dev"
    environment:
      DATABASE_HOST: storage-db
      DATABASE_PORT: 5432
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_NAME: storagedb
      RABBITMQ_URI: amqp://guest:guest@rabbitmq:5672
    networks:
      - eshop-on-web-net

  storage-db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: storagedb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - eshop-on-web-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      retries: 5
      timeout: 5s

volumes:
  postgres_data: