name: CI - Build and Test

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest

    services:
      rabbitmq:
        image: rabbitmq:3-management
        ports:
          - 5672:5672
          - 15672:15672
        options: >-
          --health-cmd "rabbitmq-diagnostics -q ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4

      # Test OrderMicroService (Python)
      - name: Test Order Microservice
        working-directory: ./MicroServices/OrderMicroService/order-service
        run: |
          python3 -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt
          pytest -q || { rc=$?; if [ $rc -eq 5 ]; then echo "No tests collected — continuing CI (exit code $rc)"; else exit $rc; fi }

      # Test CatalogMicroService (Python)
      - name: Test Catalog Microservice
        working-directory: ./MicroServices/CatalogMicroService
        run: |
          python3 -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt
          pytest -q || { rc=$?; if [ $rc -eq 5 ]; then echo "No tests collected — continuing CI (exit code $rc)"; else exit $rc; fi }

      # Test ApiGateway (Go)
      #- name: Test API Gateway
        #working-directory: ./MicroServices/ApiGatewayMicroService
        #run: |
          #go mod tidy
          #go test ./...

      # Test storage microservice (Nodejs? Antager Nodejs)
      - name: Test Storage Microservice
        working-directory: ./MicroServices/storage-micro-service
        run: |
          npm ci
          npm test || echo "No tests or ignored"

      # Test eShopOnWeb (.NET Blazor)
      #- name: Restore .NET projects
        #run: dotnet restore ./FunctionalTests.csproj
        #working-directory: ./eShopOnWeb-main/eShopOnWeb-main/tests/FunctionalTests
      
      #- name: Test .NET projects
        #run: dotnet test ./FunctionalTests.csproj --verbosity normal
        #working-directory: ./eShopOnWeb-main/eShopOnWeb-main/tests/FunctionalTests

      # Build all images using all-services.yml
      - name: Build all Docker images
        run: docker compose -f all-services.yml up --build -d
